import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import { CheckCircle2, Trophy } from "lucide-react";
import { db } from "@/lib/db";
import { requirePageUser } from "@/lib/auth/guards";
import { LABELS } from "@/lib/constants";
import { shortName } from "@/lib/format";
import { loadForUser } from "@/lib/services/interviews";
import { ButtonLink } from "@/components/ui/button";
import { Card, CardBody, CardHeader } from "@/components/ui/card";
import { Alert } from "@/components/ui/feedback";
import { InterviewerFeedbackForm } from "@/components/results/interviewer-feedback-form";
import { TranscriptView } from "@/components/room/transcript-view";

export const metadata: Metadata = { title: "Interview wrap-up" };

export default async function WrapUpPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requirePageUser({ roles: ["interviewer"] });
  const { id } = await params;
  const ctx = await loadForUser(id, user).catch(() => null);
  if (!ctx || ctx.role !== "interviewer") notFound();
  const iv = await db.interview.findUniqueOrThrow({
    where: { id },
    include: { feedback: true, student: { select: { profile: true } }, transcript: { orderBy: { createdAt: "asc" } } },
  });
  if (!["completed", "reported"].includes(iv.status)) redirect(`/interviews/${id}`);
  const points = await db.pointsEntry.aggregate({ where: { interviewId: id, userId: user.id }, _sum: { amount: true } });
  const candidate = shortName(iv.student.profile);
  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <div>
        <p className="eyebrow">{LABELS.type[iv.type]} · {iv.targetRole}</p>
        <h1 className="mt-2 flex items-center gap-3 text-3xl font-semibold text-ink-950"><CheckCircle2 className="h-7 w-7 text-olive-600" /> Interview complete</h1>
        <p className="mt-2 text-sm text-ink-500">Thanks for interviewing {candidate}. The official score is generated by AI from the transcript. Your feedback adds qualitative context.</p>
      </div>
      {iv.status === "reported" && <Alert tone="info" title="Conduct report filed">An admin will review the report. No strike is issued until then.</Alert>}
      <Card>
        <CardHeader title="Optional feedback for the candidate" description="Shared with the candidate inside their AI report." />
        <CardBody>
          {iv.feedback ? (
            <Alert tone="success" title="Feedback submitted">Your feedback will appear in {candidate}&apos;s report.</Alert>
          ) : iv.gradingStatus !== "pending" ? (
            <Alert tone="info">The feedback window has closed and the interview has been graded.</Alert>
          ) : (
            <InterviewerFeedbackForm interviewId={iv.id} />
          )}
        </CardBody>
      </Card>
      {(points._sum.amount ?? 0) > 0 && (
        <Card><CardBody className="flex items-center gap-3"><Trophy className="h-5 w-5 text-olive-600" /><p className="text-sm text-ink-700">You earned <strong>{points._sum.amount} points</strong> for this interview.</p></CardBody></Card>
      )}
      <details className="rounded-2xl border border-ink-200 bg-white shadow-card">
        <summary className="cursor-pointer px-6 py-4 text-[15px] font-semibold">Transcript</summary>
        <div className="border-t border-ink-100 px-6 py-5"><TranscriptView entries={iv.transcript} interviewerName="You" candidateName={candidate} /></div>
      </details>
      <ButtonLink href="/interviewer" variant="secondary">Back to dashboard</ButtonLink>
    </div>
  );
}
