#!/usr/bin/env node
/**
 * Runs a Prisma CLI command against the right schema for DATABASE_URL.
 *
 *   file:…          → prisma/schema.prisma (SQLite, local development)
 *   postgres(ql)://… → prisma/.generated/schema.postgres.prisma (production)
 *
 * The Postgres schema is generated from the SQLite one by swapping the
 * provider, so there is a single source of truth for the data model.
 *
 *   node scripts/db.mjs generate
 *   node scripts/db.mjs db push
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");

function databaseUrl() {
  if (process.env.DATABASE_URL) return process.env.DATABASE_URL;
  const envFile = path.join(root, ".env");
  if (!fs.existsSync(envFile)) return "";
  const line = fs.readFileSync(envFile, "utf8").split("\n").find((l) => l.trim().startsWith("DATABASE_URL="));
  return line ? line.split("=").slice(1).join("=").trim().replace(/^["']|["']$/g, "") : "";
}

const url = databaseUrl();
const isPostgres = /^postgres(ql)?:\/\//.test(url);
let schema = path.join(root, "prisma", "schema.prisma");

if (isPostgres) {
  const source = fs.readFileSync(schema, "utf8");
  const pg = source.replace(/provider\s*=\s*"sqlite"/, 'provider = "postgresql"');
  if (pg === source) throw new Error("Could not find the sqlite provider in prisma/schema.prisma");
  const outDir = path.join(root, "prisma", ".generated");
  fs.mkdirSync(outDir, { recursive: true });
  schema = path.join(outDir, "schema.postgres.prisma");
  fs.writeFileSync(schema, `// AUTO-GENERATED by scripts/db.mjs from prisma/schema.prisma, do not edit.\n${pg}`);
}

const args = [...process.argv.slice(2), "--schema", schema];
console.log(`[db] ${isPostgres ? "PostgreSQL" : "SQLite"} → prisma ${args.join(" ").replace(root + path.sep, "")}`);
const res = spawnSync("npx", ["prisma", ...args], { cwd: root, stdio: "inherit", env: process.env });
process.exit(res.status ?? 1);
